### ISSUE TITLE
Python throw an error on Vim8, on NeoVim it's ok

### ISSUE THREAD

**Issue by yusiwen** [rafi/vim-denite-session#2]
Open `Denite session` get error shown below:

```
[denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 68, in start
[denite]     self._start(sources, context)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 116, in _start
[denite]     self.gather_candidates()
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 643, in gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/denite.py", line 63, in gather_candidates
[denite]     source.context, source)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/denite.py", line 72, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/rafi/vim-denite-session/rplugin/python3/denite/source/session.py", line 48, in gather_candidat
es
[denite]     for path in globruntime(path, self.vars['pattern']):
[denite]   File "/home/yusiwen/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/util.py", line 25, in globruntime
[denite]     for rtp in re.split(',', runtimepath):
[denite]   File "/usr/lib/python3.5/re.py", line 203, in split
[denite]     return _compile(pattern, flags).split(string, maxsplit)
[denite] TypeError: cannot use a string pattern on a bytes-like object
[denite] Please execute :messages command.
```

It only occurs on Vim, on NeoVim it's OK

**Comment by rafi** [comment]
Hi @yusiwen,
I'm think this might be a denite bug with Vim, I need to investigate it further.
Meanwhile, you can use this to set the path currently:
```vim
call denite#custom#var('session', 'path', '~/.cache/vim/session')
```

Could you tell me if it works?
